name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '.github/**'
      - 'config/**'
      - 'docs/**'
      - 'images/**'
      - 'scripts/**'
      - 'tests/**'
      - '**.md'
      - '**.yml'
      - 'Makefile'

env:
  GO111MODULE: on
  GONOSUMDB: "*"
  GOSUMDB: off

jobs:
  CommitLint:
    name: commit lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5
      - name: commitlint
        uses: wagoid/commitlint-github-action@v5
      - name: style check
        run: make style_check
  UT:
    name: unit test
    needs: CommitLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.16.8'
      - name: gotest
        run: |
          go mod tidy
          make gotest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
  IntegrationTest:
    name: integration test
    needs: UT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: build and serve
        run: |
          make go_build
          bash scripts/install_cluster.sh
          ps -ef | grep ts- | grep -v grep
      - name: run integration test
        run: make IT